name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: Build wheels
      run: ./scripts/build.sh
    - name: Install twine
      run: |
        pip install twine
    - name: Publish to TestPyPI
      env:
        TWINE_USERNAME: ${{ secrets.test_pypi_username }}
        TWINE_PASSWORD: ${{ secrets.test_pypi_password }}
      run: |
        twine upload --repository testpypi --skip-existing --verbose dist/*
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: '__token__'
        TWINE_PASSWORD: ${{ secrets.pypi_password }}
      run: |
        twine upload --skip-existing --verbose dist/*
